Array

In [2]:
import numpy as np

a = np.array([[1,2], [3,4]])
b = np.array([[3,5], [5,3]])

mean = np.mean(a)
product = np.dot(a,b)

print(f"Mean: {mean}")
print(f"Product: {product}")


Mean: 2.5
Product: [[13 11]
 [29 27]]


In [4]:

matrix = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9]])
print("Original matrix:\n", matrix)

transpose = matrix.T
print("Transpose of the matrix:\n", transpose)

element_wise_multiplication = matrix * transpose
print("Element_wise multiplication:\n", element_wise_multiplication)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of the matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Element_wise multiplication:
 [[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


List

Find Max and Min Value

In [5]:
nums = [12, 34, 85, 43, 56, 86, 54, 22]
largest_value = max(nums)

print("The largest value in the given list is:", largest_value)

The largest value in the given list is: 86


In [6]:
smallest_value = min(nums)

print("The smallest value in the given list is:", smallest_value)

The smallest value in the given list is: 12


In [14]:
# Reverse the list using slicing
reversited_list = nums[::-1]

print("The reversed list used slicing function", reversited_list)

# Reverse the list using reverse function
nums.reverse()
print("The reversed list used reverse function", nums)

The reversed list used slicing function [12, 34, 85, 43, 56, 86, 54, 22]
The reversed list used reverse function [12, 34, 85, 43, 56, 86, 54, 22]


In [10]:
words = ['apple', 'kiwi', 'banana', 'apple', 'apple']
apple_count = words.count('apple')

print("The word 'apple' appears", apple_count, "time in the list")

The word 'apple' appears 3 time in the list


In [21]:
# sort a list in Python?
# using sort method

nums.sort(reverse=False)
print("The sorted list in desending order is:", nums)

nums.sort(reverse=True)
print("The sorted list in asending order:", nums)

#using sorted function

sorted_list = sorted(nums)
print("The sorted list is:", sorted_list)

The sorted list in desending order is: [12, 22, 34, 43, 54, 56, 85, 86]
The sorted list in asending order: [86, 85, 56, 54, 43, 34, 22, 12]
The sorted list is: [12, 22, 34, 43, 54, 56, 85, 86]


#Appending and Removing Elements

In [27]:
my_list = []
my_list.append(1)
my_list.append(2)
my_list.append(3)
print("After appending", my_list)

my_list.remove(2)
print("After removing", my_list)



After appending [1, 2, 3]
After removing [1, 3]


#Accessing Elements

In [28]:
fruits = ["apple", "banana", "cherry", "dates"]
print(" The second element in the list is:", fruits[1])

 The second element in the list is: banana


#Slicing

In [38]:
numbers = list(range(1,11))
print("The original list:", numbers)

scliced_numbers = numbers[2:6]
print("The scliced list:", scliced_numbers)

The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The scliced list: [3, 4, 5, 6]


Set

In [43]:
my_set = set()
my_set.add(1)
my_set.add(2)
my_set.add(3)
print("set after adding elements:", my_set)

my_set.remove(2)
print("set after removing 2:", my_set)

set after adding elements: {1, 2, 3}
set after removing 2: {1, 3}


In [46]:
set1 = {1, 2, 3, 4}
set2 = {5, 6, 1, 4}

union_set = set1.union(set2)
print("Union:", union_set)

intersection_set = set1.intersection(set2)
print("Intersection:", intersection_set)

difference_set = set1.difference(set2)
print("difference between (set1 - set2):", difference_set)

difference_set_1 = set2.difference(set1)
print("difference between (set2 - set1):", difference_set_1)

Union: {1, 2, 3, 4, 5, 6}
Intersection: {1, 4}
difference between (set1 - set2): {2, 3}
difference between (set2 - set1): {5, 6}


Tuples

In [47]:
coordinates = (40.7128, -74.0060)
latitude = coordinates[0]
longitude = coordinates[1]

print("Latitude: ", latitude)
print("Longitude: ", longitude)

Latitude:  40.7128
Longitude:  -74.006


In [52]:
# Create a tuple (Packing)
person = ("Joan", 25, "New York")

# Unpack the tuple into individual variables
name, age, city = person

# Print the unpacked values
print("Name:", name)
print("Age:", age)
print("City:", city)


Name: Joan
Age: 25
City: New York


In [53]:
%pwd


'C:\\Users\\HP'