# Array

In [2]:
import numpy as np

a = np.array([[1,2], [3,4]])
b = np.array([[3,5], [5,3]])

mean = np.mean(a)
product = np.dot(a,b)

print(f"Mean: {mean}")
print(f"Product: {product}")


Mean: 2.5
Product: [[13 11]
 [29 27]]


In [4]:

matrix = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9]])
print("Original matrix:\n", matrix)

transpose = matrix.T
print("Transpose of the matrix:\n", transpose)

element_wise_multiplication = matrix * transpose
print("Element_wise multiplication:\n", element_wise_multiplication)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of the matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Element_wise multiplication:
 [[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


# List

Find Max and Min Value

In [5]:
nums = [12, 34, 85, 43, 56, 86, 54, 22]
largest_value = max(nums)

print("The largest value in the given list is:", largest_value)

The largest value in the given list is: 86


In [6]:
smallest_value = min(nums)

print("The smallest value in the given list is:", smallest_value)

The smallest value in the given list is: 12


In [14]:
# Reverse the list using slicing
reversited_list = nums[::-1]

print("The reversed list used slicing function", reversited_list)

# Reverse the list using reverse function
nums.reverse()
print("The reversed list used reverse function", nums)

The reversed list used slicing function [12, 34, 85, 43, 56, 86, 54, 22]
The reversed list used reverse function [12, 34, 85, 43, 56, 86, 54, 22]


In [10]:
words = ['apple', 'kiwi', 'banana', 'apple', 'apple']
apple_count = words.count('apple')

print("The word 'apple' appears", apple_count, "time in the list")

The word 'apple' appears 3 time in the list


In [21]:
# sort a list in Python?
# using sort method

nums.sort(reverse=False)
print("The sorted list in desending order is:", nums)

nums.sort(reverse=True)
print("The sorted list in asending order:", nums)

#using sorted function

sorted_list = sorted(nums)
print("The sorted list is:", sorted_list)

The sorted list in desending order is: [12, 22, 34, 43, 54, 56, 85, 86]
The sorted list in asending order: [86, 85, 56, 54, 43, 34, 22, 12]
The sorted list is: [12, 22, 34, 43, 54, 56, 85, 86]


Appending and Removing Elements

In [27]:
my_list = []
my_list.append(1)
my_list.append(2)
my_list.append(3)
print("After appending", my_list)

my_list.remove(2)
print("After removing", my_list)



After appending [1, 2, 3]
After removing [1, 3]


Accessing Elements

In [28]:
fruits = ["apple", "banana", "cherry", "dates"]
print(" The second element in the list is:", fruits[1])

 The second element in the list is: banana


Slicing

In [38]:
numbers = list(range(1,11))
print("The original list:", numbers)

scliced_numbers = numbers[2:6]
print("The scliced list:", scliced_numbers)

The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The scliced list: [3, 4, 5, 6]


# Set

In [43]:
my_set = set()
my_set.add(1)
my_set.add(2)
my_set.add(3)
print("set after adding elements:", my_set)

my_set.remove(2)
print("set after removing 2:", my_set)

set after adding elements: {1, 2, 3}
set after removing 2: {1, 3}


In [46]:
set1 = {1, 2, 3, 4}
set2 = {5, 6, 1, 4}

union_set = set1.union(set2)
print("Union:", union_set)

intersection_set = set1.intersection(set2)
print("Intersection:", intersection_set)

difference_set = set1.difference(set2)
print("difference between (set1 - set2):", difference_set)

difference_set_1 = set2.difference(set1)
print("difference between (set2 - set1):", difference_set_1)

Union: {1, 2, 3, 4, 5, 6}
Intersection: {1, 4}
difference between (set1 - set2): {2, 3}
difference between (set2 - set1): {5, 6}


# Tuples

In [47]:
coordinates = (40.7128, -74.0060)
latitude = coordinates[0]
longitude = coordinates[1]

print("Latitude: ", latitude)
print("Longitude: ", longitude)

Latitude:  40.7128
Longitude:  -74.006


In [52]:
# Create a tuple (Packing)
person = ("Joan", 25, "New York")

# Unpack the tuple into individual variables
name, age, city = person

# Print the unpacked values
print("Name:", name)
print("Age:", age)
print("City:", city)


Name: Joan
Age: 25
City: New York


In [53]:
%pwd


'C:\\Users\\HP'

concatenate two tuples

In [54]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

result = tuple1 + tuple2

print(result)

(1, 2, 3, 4, 5, 6)


create tuple of tuple and find the sum of 2nd element of each tuple

In [57]:
nested_tuple = ((1, 2), (3, 4), (5, 6))

second_element_sum = sum(t[1] for t in nested_tuple)

print("The sum of second elements from the tuple:", second_element_sum)

The sum of second elements from the tuple: 12


create tuple of tuple and find the maximum element among the first nexted element

In [60]:
#nested_tuple1 = ((4, 2), (16, 4), (5, 10), (35, 100))

max_first_element = max(t[0] for t in nested_tuple)

print("The maximum value from the 1st element is :", max_first_element)



The maximum value from the 1st element is : 5


create a list of tuple with employees information such as (id, name, job title, department)

-store the data
-retrive the names with their Dept for all the employees
-create a detail of almost 4 employees

In [68]:
employees = [(1, 'Alex', 'Software Engineer', 'IT'),
        (2, 'Rob', 'HR Manager', 'HR'),
        (3, 'Tracy', 'Data Engineer', 'Analytics'),
        (4, 'Sue', 'Marketing Executive', 'Marketing')]

print("Employees Name and Department :")
for employee in employees:
    name = employee[1]
    department = employee[3]
    print(f"Name: {name}, Department: {department}")


Employees Name and Department :
Name: Alex, Department: IT
Name: Rob, Department: HR
Name: Tracy, Department: Analytics
Name: Sue, Department: Marketing


# Dictionary

Create a student database dictionary which contains the key is student name and the value is subjects

In [76]:
student = {
    'Tabu': 'Data science',
    'Arun': 'Business Management'
}

print(student)

{'Tabu': 'Data science', 'Arun': 'Business Management'}


Extract a city with maximum polulation

In [78]:
cities = {
    'New york': {'country':'USA', 'population': 87464930},
    'Los Angles': {'country': 'USA', 'population': 4690303},
    'Chicago': {'country': 'USA', 'population': 6383300030},
    'Jeddah': {'country': 'USA', 'population': 2829003636},
}
max_city_population = max(cities.items(), key=lambda x: x[1]['population'])

print(f"The city with maximum population is : {max_city_population[0]}.")
print(f"The details are : {max_city_population[1]}.")

The city with maximum population is : Chicago.
The details are : {'country': 'USA', 'population': 6383300030}.


# Panda

In [80]:
import pandas as pd
import seaborn as sns

iris = sns.load_dataset("iris")


Exploring the data

In [81]:
#display 1st few rows
print(iris.head(5))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [82]:
#display last few rows
print(iris.tail(5))

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica


In [86]:
#statistical summary
print(iris.describe(include='all'))

        sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN


In [91]:
#missing value
print(iris.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64


Basic operation

In [93]:
#selecting the data

#by single column

species_column = iris['species']
print(species_column)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [97]:
#by multiple column
selected_column = iris[['species', 'sepal_length']]
print(selected_column)

       species  sepal_length
0       setosa           5.1
1       setosa           4.9
2       setosa           4.7
3       setosa           4.6
4       setosa           5.0
..         ...           ...
145  virginica           6.7
146  virginica           6.3
147  virginica           6.5
148  virginica           6.2
149  virginica           5.9

[150 rows x 2 columns]


In [98]:
#by row index
first_three_rows = iris.iloc[:3]
print(first_three_rows)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa


In [100]:
#selecting the specific rows
specific_row = iris.iloc[[0, 2, 3, 4]]
print(specific_row)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [103]:
#selecting the specific rows and colums
specific_row_col = iris.iloc[0:3, 0:2]
print(specific_row_col)

   sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2


In [106]:
#filtering
filtered_data = iris[iris['sepal_length'] > 5]
print(filtered_data)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[118 rows x 5 columns]


In [107]:
filtered_data = iris[iris['petal_length'] > 5]
print(filtered_data)

     sepal_length  sepal_width  petal_length  petal_width     species
83            6.0          2.7           5.1          1.6  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
111           6.4          2.7           5.3          1.9   virginica
112           6.8          3.0           5.5          2.1   virginica
114           5.8   

In [113]:
#sorting data
sorting_data_asc = iris.sort_values(by='sepal_length')
sorting_data_desc = iris.sort_values(by='petal_length', ascending=False)
print(sorting_data_asc)

print(sorting_data_desc)


     sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]
     sepal_length  sepal_width  petal_length  petal_width    species
118           7.7          2.6           6.9          2.3  virginica
122       

In [115]:
#Modifying data

#adding a new column
iris['sepal_area'] = iris['sepal_length'] * iris['sepal_width']
print(iris.head())

   sepal_length  sepal_width  petal_length  petal_width species  sepal_area
0           5.1          3.5           1.4          0.2  setosa       17.85
1           4.9          3.0           1.4          0.2  setosa       14.70
2           4.7          3.2           1.3          0.2  setosa       15.04
3           4.6          3.1           1.5          0.2  setosa       14.26
4           5.0          3.6           1.4          0.2  setosa       18.00


In [117]:
#drop a column
iris.drop(columns=['sepal_area'], inplace = True)
print(iris.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [118]:
#Aggregation and groupBy
avg = iris.groupby('species').mean()
print(avg)

            sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026


In [126]:
#save the data
iris.to_csv('iris_data_csv',index=False)

iris.to_excel('iris_data.xlsx', index=False)
